### ISSUE TITLE
For new beginner.

### ISSUE THREAD

**Issue by jcs090218** [sstokic-tgm/JFTSE#11]
Sorry to have this issue opened! As both me and you mentioned in this thread #5, is there any article that may help develop this project? 😖 Although I am game programmer and do both on client and server side, yet I do not have any experience on developing a private server just by having no idea on cracking/analyzing the packet from an already built executable!

I have read through [AnCoFT](https://github.com/AnCoFT/AnCoFT)'s README file and I notice we need `x64dbg` and `Ghidra`. I have very minimal knowledge to `x64dbg` yet I never heard of `Ghidra`!

What would you suggest people like me (or just me) to read through in order to help develop this project further? Maybe tutorial, article, etc? 😕 

And thanks again for your hard work! 😄

**Comment by sstokic-tgm** [comment]
x64dbg is used for runtime analysis.

Ghidra is just a free software for statical analysis, there is also IDA Pro but it's not free. 

An example for utilizing both:
You are working on a Packet XY and you have no idea how the game uses the info you sent (and want to understand what you are sending), you then use x64dbg for instance and place breakpoints in the functions you found in IDA or Ghidra. x64dbg will tell you from the runtime the addresses where it's written etc.
Then you can use ReClass for example to build a structure of the player pointer, so you for example know, if the statical analysis say 'playerPointer + <some offset> = packet + <packet offset>' , you will know that the data you wrote in the packet at the second, third etc. position is writing to HP, STR etc. 

It sounds confusing maybe, but it's not if you get it :)

Knowledge in these things should be:
ASM (atleast basics), how pointers work in the C/C++ language, virtual tables and knowing the game somehow (since we are reconstructing everything without an live server).

Some articles on it:
https://www.cheathappens.com/tut_assembly.asp?tutID=9
http://www.cplusplus.com/doc/tutorial/pointers/
https://en.m.wikipedia.org/wiki/Virtual_method_table

What you can do is, for example look at one of the existing Packets. Search for the packet id in your statical analysis tool (the game either switch-cases it or does if-checks on packet id's), look in what order I write data in the packet and look how it gets read & used. You will get an idea how it works :)

I am bad at write-ups, so if something is unclear just ask :D
