### ISSUE TITLE
the user id is blocked   code=4002, -6

### ISSUE THREAD

**Issue by ldlv587** [sstokic-tgm/JFTSE#163]
whats going on here , pls   my account   :ldlv587 and ldlav587  ..the same problem 
![QQ图片20230314010025](https://user-images.githubusercontent.com/127360092/224773462-77a17574-613c-4ed3-92c1-146ee5629fc9.png)

**Comment by viol3** [comment]
Your account(s) has been banned for 3 days because of violation farming rule. You can check discord #jftse-public-log

**Comment by ldlv587** [comment]
ok  Well, I've lost my ability to add the wrong stats and want to build another pure power character lucy, but no one wants to play with me at level 1, so I'll have to get to level 10 or so

**Comment by viol3** [comment]
You can request games from other players/GMs with other channels like #looking-for-game .
Both players seadragonfly & bmeteorite was staying idle and making no actions, just waiting for match end, its restricted. This turns out to be unfair next to other players trying to earn RP by playing normally.

**Comment by ldlv587** [comment]
by the way,where is discord #jftse-public-log and discord #jftse-events ,i  really checked every option,

**Comment by ldlv587** [comment]
Well, I won't do it again and the upgrade is super slow

**Comment by viol3** [comment]
You need to accept rules in #rules section

**Comment by ldlv587** [comment]
Didn't I click Accept？ok i go to see
