### ISSUE TITLE
Issues from Discord and FB Group 28072020

### ISSUE THREAD

**Issue by Thewimo** [sstokic-tgm/JFTSE#2]
- When you get into Deuce/adv-40 and win this set, the match won't continue with the 2nd set and instead you win the whole match
(vice versa with losing)
exiting right afterwards unlocks the next
- the longer you play the battle mode, the less damage spells do
"Currently all spells do 1 dmg and i am not even on stage 20"
(I would have said that the higher the stage the higher the rest. Based on compaing the green souls attack)
- Discord User "Milov" experienced being level 0 at one point
- NPC and guardian share the same HP pool & damaging guardian is possible (with meteor but not with blind)
- Wing of Memory Item Feature (Stats reset) has yet to be implemented

**Comment by milov-afk** [comment]
- Whenever (while logged in) the Game Client Process is terminated (End Task, Client Crash, etc.), you are not able to login back successfuly. 
Client Response: This user id is currently logged on. Please try again later. ( code = 4002, -2 )
Temporarly fix: Access JFTSE's Portal on http://148.251.23.217/ft/ , on Status Reset container, insert your username (Login ID) in the text box and press "Reset" button.

**Comment by sstokic-tgm** [comment]
I tagged it as enchancement, since a lot of things here are "to implement".

With the commit 9a997fb9 these things were fixed from here:
-) Deuce working now
-) dc/client crash etc shouldn't not give status logged in anymore

**Comment by Thewimo** [comment]
Updating it now then:

- the longer you play the battle mode, the less damage spells do
"Currently all spells do 1 dmg and i am not even on stage 20"
(I would have said that the higher the stage the higher the rest. Based on compaing the green souls attack)
- Discord User "Milov" experienced being level 0 at one point
~~- NPC and guardian share the same HP pool & damaging guardian is possible (with meteor but not with blind)~~
- Wing of Memory Item Feature (Stats reset) has yet to be implemented
- Lobby Room creation with empty names:
After pressing the "Create" room you get disconnected from the server.
https://im7.ezgif.com/tmp/ezgif-7-43bf051852ae.gif
https://im7.ezgif.com/tmp/ezgif-7-4ca57ece0cbf.gif
- Switching slots/changing sides into a room, locks  you there.
https://im7.ezgif.com/tmp/ezgif-7-a9a482f3179d.gif

**Comment by Thewimo** [comment]
Updating it now then:

- the longer you play the battle mode, the less damage spells do
"Currently all spells do 1 dmg and i am not even on stage 20"
(I would have said that the higher the stage the higher the rest. Based on compaing the green souls attack)
- Discord User "Milov" experienced being level 0 at one point
- ~~NPC and guardian share the same HP pool & damaging guardian is possible (with meteor but not with blind)~~
- Wing of Memory Item Feature (Stats reset) has yet to be implemented
- Lobby Room creation with empty names:
After pressing the "Create" room you get disconnected from the server.
https://im7.ezgif.com/tmp/ezgif-7-43bf051852ae.gif
https://im7.ezgif.com/tmp/ezgif-7-4ca57ece0cbf.gif
- Switching slots/changing sides into a room, locks  you there.
https://im7.ezgif.com/tmp/ezgif-7-a9a482f3179d.gif
- Enhancement feature has yet to be implemented (Success doesnt change stats)
- When you try to shop the vampire pg, or style him, the name that it shown is not “Dhanpir” but “Dennis”.
- In Single Play, the lv 9 of Dhanpir, lv 10 of Shua, lv 7 and 27 of the Arena, lv 10 of Niki in Battle Mode are not counted as won.
- Battlemon feature has yet to be implemented
- The players starts at lv 20. A pg at lv 20 should have about 260 HP, and in the pg info I have 257 HP, but during Battle Mode in Single Play my pg has only 200 HP.
- Sometimes the reward items that I obtain at the end of a match are different from the one I was supposed to get.
- my pg seemed to have the equipment on, but when I opened the pocket I found out that he wasn't wearing it.

(- During Battle Mode in Single Play, sometimes when a meteor falls in my part of the field it removes HP to the opponent player. And sometimes the guardian disappears for no reason and I have to kill the opponent players with spells.)

Editing for general POV will be done in a few hours.

**Comment by sstokic-tgm** [comment]
Updating the list:

### **Bugs:**
- the longer you play the battle mode, the less damage spells do
"Currently all spells do 1 dmg and i am not even on stage 20"
(I would have said that the higher the stage the higher the rest. Based on compaing the green souls attack)
- ~~Discord User "Milov" experienced being level 0 at one point~~
- ~~NPC and guardian share the same HP pool & damaging guardian is possible (with meteor but not with blind)~~
- ~~When you try to shop the vampire pg, or style him, the name that it shown is not “Dhanpir” but “Dennis”.~~ **_-> Related to the game client. Dhanpir = Dennis, since the most recent client is Thai, we have Dennis written._**
- In Single Play, the lv 9 of Dhanpir, lv 10 of Shua, lv 7 and 27 of the Arena, lv 10 of Niki in Battle Mode are not counted as won.
- ~~The players starts at lv 20. A pg at lv 20 should have about 260 HP, and in the pg info I have 257 HP, but during Battle Mode in Single Play my pg has only 200 HP.~~
- Sometimes the reward items that I obtain at the end of a match are different from the one I was supposed to get.
- ~~my pg seemed to have the equipment on, but when I opened the pocket I found out that he wasn't wearing it.~~
- ~~(During Battle Mode in Single Play, sometimes when a meteor falls in my part of the field it removes HP to the opponent player. And sometimes the guardian disappears for no reason and I have to kill the opponent players with spells.)~~ **_-> Related to the game client._**


### **Missing:**
- Wing of Memory Item Feature (Stats reset) has yet to be implemented
- Enhancement feature has yet to be implemented (Success doesnt change stats)
- Battlemon feature has yet to be implemented
- Rooms


**Room specific stuff removed from the list, as it is going to be reworked.**
