### ISSUE TITLE
It s really hard to enter the game...Also If you wait 10 Min or 20

### ISSUE THREAD

**Issue by linlin08** [sstokic-tgm/JFTSE#49]

**Comment by ivan7208** [comment]
The game is currently in a very unstable version, a lot of crashes happen very frequently, hence why the server does not stop to crash. It is normal for everyone to access the game when it is active, because it is constantly being crashed with a lot of bugs. Do not expect to have a stable version of the game and play immediately, be patient and help the community to solve those kind of bugs to improve the stability of the game so it does not crash that often. 

Cheers.
