### ISSUE TITLE
Game crashes once the match launches

### ISSUE THREAD

**Issue by hieualan1** [sstokic-tgm/JFTSE#56]
Hi, I deleted the old files and downloaded the FT_Launcher as it's in the instructions of the newest YT video. Once I launched the FT_Launcher I have the new files downloaded and then I logged in and created a room. Once I press ready, the countdown goes off and once the map is about to launch the game crashes and I get the notification of getting disconnected. Please, is there any solution or? Thanks a lot

**Comment by milov-afk** [comment]
This issue is not client-side. The matchmade games server might be down for maintenance/debugging. Don't take the multiplayer as granted, is not fully launched, the Server is written from scratch and many bugs may occur until a stable version is made. The Server is currently under testing state. What you described is a well known thing that happens when matchmaking games are unable to proceed(match cannot be played). For more information, give an eye on the discussions on Discord channel.

**Comment by sstokic-tgm** [comment]
Does the problem still exist?

**Comment by Davingi** [comment]
Closing this issue since this bug didn't occur in the last few weeks anymore. In case it happens again we can reopen this issue.
