### ISSUE TITLE
Gacha bug

### ISSUE THREAD

**Issue by LolaPinqui** [sstokic-tgm/JFTSE#61]
I was opening gacha balls when the strange purple ball with stars appeared and my game crashed.
![2021-01-31_235733](https://user-images.githubusercontent.com/78322813/106397940-13928580-6421-11eb-840f-f6ec9ecbfe6a.png)
Also, I don't actually know if it is a bug, but I often face another problem: I win many clothes that I already have again, also it is extremely rare to win a clothing item.
                 * I was using only RED COINS

**Comment by sstokic-tgm** [comment]
This happens when the game server crashes midwhile.
It shows you that you won the same item, but it's not saved to your inventory since you have one already. And gacha doesn't cause crashes, so don't worry.
It's rare to win a clothing item because of the odds, you can look them up here: https://github.com/sstokic-tgm/JFTSE/tree/master/src/main/resources/res/lottery
(They are FT Thai original untouched)
Ofcourse the lottery system will be improved in future, to instead of getting the same item, to reroll the lottery!
