### ISSUE TITLE
Private Server Question

### ISSUE THREAD

**Issue by angvamberg** [sstokic-tgm/JFTSE#63]
Hello! I created a private server that is running on a VPS (ubuntu). 
I'm able to login, create character, use shop, chat and play singlemode, but I get error whenever I try to play with a friend:

"Sorry, it has a server connection problem now. (code = 1002, -1)"

By the way, I've tried to disable firewall and allow tcp/udp requests... 
Is there any configuration needed to fix that?

Thanks!

**Comment by Davingi** [comment]
Make sure to put in the IP address here under which your server is reachable. 

https://github.com/sstokic-tgm/JFTSE/blob/cf35c6dd87a6fa9469ec97e88821a28f1386c69a/src/main/java/com/ft/emulator/server/game/core/game/handler/GamePacketHandler.java#L1287

Currently it's hardcoded into the code and obviously is a bad design. But for now getting stuff to work was a higher priority for us. If this fixes it for you let me know so that I can close this issue.

**Comment by angvamberg** [comment]
It worked perfectly. Tyy!!
