### ISSUE TITLE
play multiplayer ?

### ISSUE THREAD

**Issue by stank2010** [sstokic-tgm/JFTSE#7]
How can we turn this server to multiplayer ?

**Comment by sstokic-tgm** [comment]
The server is already multiplayer, otherwise you wouldn't be able to login, use the shop etc.

If you mean with multiplayer the game mode, then it's still on work and there is no ETA when it's ready.
-> How to turn it to multiplayer?
By contributing to it (which means, reversing multiplayer code + extending the existing code with the new one to accomplish that functionality) or by waiting for it till I finish.

If I answered your question, please feel free to close this issue.

**Comment by stank2010** [comment]
Thanks!
